vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0002_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0002_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0002_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0002_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0002_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0002_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0002_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0002_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0002_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0002_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0002_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0002_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0014_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0014_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0014_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0014_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0014_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0014_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0014_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0014_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0014_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0014_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0014_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0014_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0019_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0019_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0019_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0019_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0019_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0019_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0019_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0019_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0019_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0019_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0019_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0019_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0020_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0020_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0020_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0020_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0020_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0020_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0020_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0020_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0020_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0020_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0020_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0020_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0021_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0021_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0021_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0021_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0021_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0021_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0021_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0021_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0021_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0021_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0021_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0021_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0022_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0022_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0022_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0022_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0022_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0022_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG0022_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0022_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0022_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0022_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0022_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG0022_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG04_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG04_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG04_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG04_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG04_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG04_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG04_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG04_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG04_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG04_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG04_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG04_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG09_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG09_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG09_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG09_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG09_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG09_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG09_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG09_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG09_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG09_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG09_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG09_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG10_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG10_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG10_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG10_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG10_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG10_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG10_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG10_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG10_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG10_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG10_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG10_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG11_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG11_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG11_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG11_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG11_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG11_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG11_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG11_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG11_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG11_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG11_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG11_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG12_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG12_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG12_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG12_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG12_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG12_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG12_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG12_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG12_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG12_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG12_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG12_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG13_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG13_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG13_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG13_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG13_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG13_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG13_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG13_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG13_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG13_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG13_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG13_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG15_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG15_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG15_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG15_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG15_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG15_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG15_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG15_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG15_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG15_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG15_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG15_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG17_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG17_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG17_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG17_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG17_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG17_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG17_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG17_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG17_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG17_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG17_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG17_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG18_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG18_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG18_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG18_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG18_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG18_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BG18_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG18_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG18_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG18_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG18_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BG18_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0002_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0002_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0002_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0002_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0002_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0002_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0002_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0002_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0002_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0002_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0002_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0002_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0003_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0003_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0003_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0003_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0003_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0003_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0003_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0003_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0003_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0003_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0003_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0003_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0004_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0004_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0004_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0004_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0004_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0004_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0004_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0004_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0004_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0004_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0004_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0004_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0005_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0005_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0005_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0005_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0005_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0005_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0005_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0005_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0005_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0005_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0005_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0005_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0006_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0006_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0006_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0006_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0006_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0006_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0006_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0006_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0006_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0006_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0006_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0006_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0008_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0008_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0008_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0008_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0008_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0008_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0008_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0008_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0008_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0008_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0008_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0008_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0009_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0009_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0009_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0009_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0009_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0009_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0009_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0009_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0009_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0009_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0009_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0009_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0010_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0010_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0010_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0010_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0010_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0010_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0010_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0010_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0010_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0010_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0010_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0010_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0011_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0011_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0011_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0011_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0011_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0011_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0011_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0011_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0011_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0011_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0011_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0011_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0012_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0012_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0012_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0012_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0012_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0012_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0012_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0012_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0012_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0012_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0012_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0012_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0013_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0013_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0013_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0013_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0013_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0013_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0013_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0013_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0013_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0013_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0013_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0013_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0015_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0015_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0015_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0015_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0015_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0015_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0015_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0015_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0015_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0015_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0015_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0015_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0016_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0016_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0016_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0016_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0016_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0016_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0016_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0016_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0016_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0016_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0016_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0016_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0017_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0017_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0017_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0017_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0017_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0017_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0017_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0017_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0017_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0017_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0017_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0017_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0018_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0018_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0018_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0018_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0018_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0018_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0018_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0018_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0018_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0018_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0018_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0018_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0019_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0019_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0019_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0019_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0019_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0019_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0019_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0019_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0019_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0019_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0019_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0019_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0020_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0020_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0020_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0020_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0020_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0020_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0020_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0020_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0020_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0020_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0020_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0020_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0021_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0021_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0021_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0021_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0021_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0021_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0021_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0021_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0021_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0021_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0021_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0021_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0022_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0022_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0022_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0022_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0022_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0022_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0022_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0022_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0022_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0022_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0022_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0022_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0023_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0023_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0023_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0023_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0023_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0023_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0023_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0023_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0023_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0023_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0023_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0023_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0024_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0024_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0024_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0024_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0024_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0024_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0024_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0024_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0024_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0024_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0024_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0024_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0025_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0025_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0025_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0025_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0025_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0025_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0025_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0025_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0025_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0025_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0025_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0025_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0026_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0026_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0026_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0026_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0026_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0026_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0026_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0026_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0026_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0026_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0026_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0026_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0027_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0027_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0027_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0027_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0027_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0027_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0027_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0027_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0027_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0027_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0027_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0027_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0029_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0029_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0029_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0029_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0029_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0029_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0029_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0029_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0029_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0029_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0029_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0029_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0030_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0030_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0030_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0030_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0030_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0030_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0030_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0030_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0030_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0030_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0030_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0030_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0031_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0031_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0031_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0031_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0031_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0031_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0031_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0031_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0031_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0031_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0031_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0031_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0032_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0032_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0032_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0032_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0032_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0032_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0032_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0032_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0032_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0032_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0032_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0032_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0033_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0033_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0033_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0033_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0033_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0033_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0033_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0033_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0033_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0033_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0033_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0033_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0034_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0034_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0034_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0034_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0034_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0034_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0034_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0034_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0034_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0034_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0034_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0034_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0035_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0035_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0035_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0035_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0035_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0035_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0035_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0035_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0035_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0035_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0035_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0035_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0036_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0036_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0036_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0036_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0036_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0036_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0036_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0036_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0036_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0036_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0036_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0036_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0037_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0037_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0037_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0037_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0037_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0037_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0037_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0037_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0037_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0037_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0037_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0037_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0038_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0038_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0038_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0038_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0038_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0038_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0038_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0038_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0038_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0038_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0038_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0038_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0039_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0039_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0039_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0039_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0039_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0039_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0039_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0039_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0039_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0039_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0039_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0039_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0040_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0040_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0040_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0040_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0040_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0040_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BH0040_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0040_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0040_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0040_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0040_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BH0040_Right.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BI0001_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BI0001_Left.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BI0001_Left.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BI0001_Left.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BI0001_Left.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BI0001_Left.vtk
vmtkcenterlineresampling -length 0.05 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\BI0001_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BI0001_Right.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BI0001_Right.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BI0001_Right.vtk
vmtksurfacewriter -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BI0001_Right.vtk -mode ascii -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\scaling\\resamp_attr_ascii\\vmtkgeometry\\BI0001_Right.vtk
