vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_000_-5.268.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_000_-5.268.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_000_-5.268.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_000_-5.268.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_001_-3.996.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_001_-3.996.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_001_-3.996.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_001_-3.996.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_002_-2.723.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_002_-2.723.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_002_-2.723.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_002_-2.723.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_003_-1.451.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_003_-1.451.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_003_-1.451.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_003_-1.451.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_004_-0.178.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_004_-0.178.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_004_-0.178.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_004_-0.178.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_005_1.094.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_005_1.094.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_005_1.094.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_005_1.094.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_006_2.367.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_006_2.367.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_006_2.367.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_006_2.367.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_007_3.64.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_007_3.64.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_007_3.64.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_007_3.64.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_008_4.912.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_008_4.912.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_008_4.912.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_008_4.912.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_009_6.185.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_009_6.185.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_009_6.185.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC1\\PC1_009_6.185.vtk
