vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_000_-3.785.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_000_-3.785.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_000_-3.785.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_000_-3.785.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_001_-2.461.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_001_-2.461.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_001_-2.461.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_001_-2.461.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_002_-1.138.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_002_-1.138.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_002_-1.138.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_002_-1.138.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_003_0.186.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_003_0.186.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_003_0.186.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_003_0.186.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_004_1.509.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_004_1.509.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_004_1.509.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_004_1.509.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_005_2.832.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_005_2.832.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_005_2.832.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_005_2.832.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_006_4.156.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_006_4.156.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_006_4.156.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_006_4.156.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_007_5.479.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_007_5.479.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_007_5.479.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_007_5.479.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_008_6.803.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_008_6.803.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_008_6.803.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_008_6.803.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_009_8.126.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_009_8.126.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_009_8.126.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\PC2\\PC2_009_8.126.vtk
