vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_000.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_000.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_000.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_000.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_005.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_005.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_005.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_005.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_010.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_010.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_010.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_010.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_015.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_015.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_015.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_015.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_020.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_020.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_020.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_020.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_025.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_025.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_025.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_025.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_030.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_030.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_030.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_030.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_035.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_035.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_035.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_035.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_040.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_040.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_040.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_040.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_045.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_045.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_045.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_045.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_050.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_050.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_050.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_050.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_055.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_055.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_055.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_055.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_060.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_060.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_060.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_060.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_065.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_065.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_065.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_065.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_070.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_070.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_070.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_070.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_075.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_075.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_075.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_075.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_080.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_080.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_080.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_080.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_085.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_085.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_085.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_085.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_090.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_090.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_090.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_090.vtk
vmtkcenterlinegeometry -smoothing 1 -iterations 300 -factor 0.1 -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_095.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_095.vtk
vmtkcenterlineattributes -ifile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_095.vtk -ofile D:\\!BraVa_src\\src\\ModeDecomposition\\synthetic_vessels\\circle\\circle_095.vtk
